### ISSUE TITLE
Online-Demo

### ISSUE THREAD

**Issue by M4Z3** [rchampourlier/idea_zone#1]
Hi!
I'm very interested to see what kind of idea platform you have created. But unfortunately, I'm not familiar with the technologies used to build this platform. Is there a chance to give me a quick visual overview? I would appreciate it! 

Thanks!

**Comment by rchampourlier** [comment]
Hi @M4Z3,

Thanks for your interest. Sorry for the delay, I'm not working on this project anymore. However you can still find a running instance [here](https://ideas-sgc.herokuapp.com).

Hope you'll enjoy, though it remains a really basic solution!

Cheers,
